### ISSUE TITLE
about kernel_size and stride in PConv

### ISSUE THREAD

**Issue by liamsun2019** [JierunChen/FasterNet#5]
Hi author，

Thanks for your great work. Just curious about the kernel size and stride configurations of PConv sample code in your paper. Looks that the stride is always set to 1 while kernel size set to 3. Have you conducted experiments with other stride/kernel_size？I'm thinking about replacing any regular convs with different kernel/stride values. Appreicate your comments. Thanks.

**Comment by JierunChen** [comment]
Thanks for your interest. We fix stride to 1 to keep the spatial dimension unchanged. Otherwise, the convolutional output cannot be directly concatenated with the remaining channels. For downsampling, FasterNet adopts regular Convs. 

For other kernel_size, we did not try related experiments as the complexity is quadratically related to the kernel_size.
